### ISSUE TITLE
Question about xsecurelock, xss-lock, xscreensaver bundle

### ISSUE THREAD

**Issue by thepenguinthatwants** [kipfstuhl/dotfiles#1]
Hiya!

I am not sure if its okay to ask here. But I am using i3 and i3lock and thought about trying something else and somehow stumbled on your repo.

Tried to look around your configs but couldn't find the relevant information about xsecurelock, xss-lock, xscreensaver bundle.

Can you give some examples or tell me where are those configs found or how it is implemented?

**Comment by kipfstuhl** [comment]
Hi,

of course it is OK to ask here, where else should you?

These programs work directly with the X server, the relevant file is the configuration file for Xorg [~/.xinitrc](https://github.com/kipfstuhl/dotfiles/blob/master/Xorg/.xinitrc#L61).

These are the two relevant lines
```
    xset s 300 20
    xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_SAVER=saver_xscreensaver xsecurelock &
```


`xset s` is just the tool to set the X server preferences for screensavers. Here it is 300 seconds to turn the screensaver on.
You can also use `xset s on` or `xset s activate` to directly lock the screen, this is useful for a keyboard shortcut.

The other command `xss-lock ...` is for telling X to use a locker. Here the xsecurelock is used and as an environment variable the screensaver is given to xsecurelock. (This is not really useful, but I was too lazy to change it. xsecurelock works perfectly without a screensaver)

If you want a good description of xsecurelock and how it works with the two others see its repository https://github.com/google/xsecurelock

I hope this could help.

**Comment by thepenguinthatwants** [comment]
Hi!

As I use sddm as login manager so I guess it doesnt work on .xinitrc. I tried it on .profile but it seems that also was not good enough. I actually got something to happen when I put it all as a oneliner in i3wm but my screen just dimmed after the 300 seconds and I couldnt get it back up it was just dimmed.

But thanks for showing how it works on your setup.

**Comment by kipfstuhl** [comment]
With your description I think xss-lock works. But xscreensaver does not play well.
Was the display dimmed with black sqares or was is black? And if you used the line directly did xscreensaver start? Maybe the problem is that xss-lock or xsecurelock could not start xscreensaver correctly and it hangs in this stage. It could work if you just omit the `env XSECURELOCK_SAVER=saver_xscreensaver` part.

I have no idea how to configure sddm. In the Archwiki there a [hint](https://wiki.archlinux.org/index.php/Display_manager#Run_~/.xinitrc_as_a_session) to a solution for having xinitrc as a session for a display manager. Maybe it can be done directly with sddm configuration.

If want to you can have a look at nathbo's [dotfiles](https://github.com/nathbo/dotfiles/blob/73ee657ee6fb562628556b4ce2824887e69ac05d/dotfiles/config/i3/config#L90). He uses i3 with xsecurelock. But I don't know whether he uses a display manger.
